#!/bin/bash
echo " enter the file name "
read file
find /home/ec2-user -iname "$file" > location-$file
if [ $? -eq 0 ];then
	echo "$file is found in below location"
	cat location-$file
	rm location-$file
else
	echo " file is not found in any location "
fi
